#! /usr/bin/env bash
# Test 'file_writer' to see if it will write a partial file occasionally when
# it is 'kill -9'-d.

truncate -s0 results
for i in {1..1000}; do
    rm data 2>/dev/null
    ./file_writer data "$@" &
    PID=$!

    # Wait for a similar amount of time as our background './file_writer'
    # should take before sending it SIGKILL, this way we have a good chance of
    # killing it during writing occasionally.
    ./file_writer test "$@"

    kill -9 $PID 2>/dev/null
    wait $PID 2>/dev/null
    rm test

    OUTPUT=$(wc -c data 2>/dev/null)
    if [[ -z "${OUTPUT}" ]]; then
        # no file
        printf '.'
        echo '.' >> results
    else
        if [[ "${OUTPUT}" == "9600 data" ]]; then
            # complete file
            printf '_'
            echo '_' >> results
        else
            # partial file - this is bad
            printf 'X'
            echo 'X' >> results
        fi
    fi
done
echo
rm data 2>/dev/null
rm tmp* 2>/dev/null
sort results | uniq -c
rm results
# -----------------------------------------------------------------------------
# Copyright (C) 2016 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------ END-OF-FILE ----------------------------------
