#!/usr/bin/env python
# encoding: utf-8

"""abd automates the creation and landing of reviews from branches"""

import argparse
import sys

import abdcmd_default
import phlsys_subprocess


def main():
    parser = argparse.ArgumentParser(
        description="Phabricator Instance tool")

    parser.add_argument('instance', type=str)
    args = parser.parse_args()

    print "fetch"
    phlsys_subprocess.runCommands("git fetch -p")
    print "process"
    abdcmd_default.processUpdatedRepo(".", args.instance)

if __name__ == "__main__":
    sys.exit(main())
