#!/usr/bin/env python
# encoding: utf-8

"""abd automates the creation and landing of reviews from branches"""

import argparse
import sys
import time

import abdcmd_default
import abdmail_printsender
import abdmail_mailer
import phlsys_conduit
import phlsys_subprocess


def main():
    parser = argparse.ArgumentParser(
        description="Arcanist Branch Daemon")

    # TODO: add help messages
    parser.add_argument('--instance-uri', type=str, required=True)
    parser.add_argument('--abd-user', type=str, required=True)
    parser.add_argument('--abd-certificate', type=str, required=True)
    parser.add_argument('--abd-email', type=str, required=True)
    parser.add_argument('--admin-email', type=str, required=True)
    parser.add_argument('--repo-description', type=str, required=True)
    parser.add_argument('--https-proxy', type=str)
    parser.add_argument('--sleep-duration-secs', type=int, default=60)
    args = parser.parse_args()

    print_sender = abdmail_printsender.MailSender(args.abd_email)
    mailer = abdmail_mailer.Mailer(
        print_sender,
        [args.admin_email],
        args.repo_description)

    conduit = phlsys_conduit.Conduit(
        args.instance_uri,
        args.abd_user,
        args.abd_certificate,
        https_proxy=args.https_proxy)

    while True:
        print "fetch"
        phlsys_subprocess.runCommands("git fetch -p")
        print "process"
        abdcmd_default.processUpdatedRepo(conduit, ".", "origin", mailer)
        sleep_remaining = args.sleep_duration_secs
        while sleep_remaining > 0:
            sys.stdout.write("\rsleep (" + str(sleep_remaining) + " seconds) ")
            sys.stdout.flush()
            time.sleep(1)
            sleep_remaining -= 1
        sys.stdout.write(
            "\rslept " + str(args.sleep_duration_secs) + " seconds  \n")
        sys.stdout.flush()


if __name__ == "__main__":
    sys.exit(main())

#------------------------------------------------------------------------------
# Copyright (C) 2012 Bloomberg L.P.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#------------------------------- END-OF-FILE ----------------------------------
