#!/usr/bin/env python
# encoding: utf-8

"""Phab Ping  - a Phabricator conduit.ping wrapper

This allows you to check that Phabricator instances are running as expected.
"""

_USAGE_EXAMPLES = """
usage examples:
    ping the official Phabricator install once:
    $ ./phab-ping https://secure.phabricator.com/

    ping the local Phabricator install once:
    $ ./phab-ping http://127.0.0.1/api/

    Note that the trailing slash is required.
"""

import argparse
import sys
import time

import phlsys_conduit


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=__doc__,
        epilog=_USAGE_EXAMPLES)

    parser.add_argument(
        'address',
        metavar="URI",
        type=str,
        help="address of the Phabricator API, e.g. "
        "https://secure.phabricator.com/api/. "
        "Note that the trailing slash is required.")

    args = parser.parse_args()

    # TODO: handle URIs more robustly, shoudn't require /api/ at the end
    #       can print URI we actually use if we extrapolate for the user

    # perform the ping and display the time taken and result
    start = time.time()
    conduit = phlsys_conduit.Conduit(args.address)
    result = conduit.ping()
    end = time.time()
    msecs = (end - start) * 1000
    print str(int(msecs)) + " msecs : " + result


if __name__ == "__main__":
    sys.exit(main())

#------------------------------------------------------------------------------
# Copyright (C) 2012 Bloomberg L.P.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#------------------------------- END-OF-FILE ----------------------------------
