#! /usr/bin/env bash
usage='usage: on_system_error.sh IDENTIFIER DETAIL'

# look at py/abd/abdt_errident.py for a list of possible error identifiers

# the identifier is a short string to identify the tryloop that failed
# the description should contain enough context to begin debugging the error

if [ $# -ne 2 ]; then
    echo "${usage}"
    exit 2
fi

identifier=$1
multiline_detail=$2
detail=$(echo "${multiline_detail}" | tr "\n" " ")

echo "on_system_error:"
echo "  identifier: ${identifier}"
echo "  detail: ${detail}"

echo ========================================================== >> logerror.txt
echo -------------------------- LOG ERROR --------------------- >> logerror.txt
echo "identifier: $1" >> logerror.txt
echo "description: $2" >> logerror.txt
echo ========================================================== >> logerror.txt
echo >> logerror.txt


#------------------------------------------------------------------------------
# Copyright (C) 2014 Bloomberg Finance L.P.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#------------------------------- END-OF-FILE ----------------------------------
