#! /usr/bin/env bash
usage='usage: on_system_error.sh IDENTIFIER DETAIL'

# look at py/abd/abdt_errident.py for a list of possible error identifiers

# the identifier is a short string to identify the tryloop that failed
# the description should contain enough context to begin debugging the error

if [ $# -ne 2 ]; then
    echo "${usage}"
    exit 2
fi

identifier=$1
multiline_detail=$2
detail=$(echo "${multiline_detail}" | tr "\n" " ")

echo "on_system_error:"
echo "  identifier: ${identifier}"
echo "  detail: ${detail}"

echo ========================================================== >> logerror.txt
echo -------------------------- LOG ERROR --------------------- >> logerror.txt
echo "identifier: $1" >> logerror.txt
echo "description: $2" >> logerror.txt
echo ========================================================== >> logerror.txt
echo >> logerror.txt


# -----------------------------------------------------------------------------
# Copyright (C) 2014 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------ END-OF-FILE ----------------------------------
