#!/usr/bin/env python
# encoding: utf-8

"""Maily - a sendmail wrapper

Intended primarily to test our sendmail integration, this can also be used
as a very simple wrapper around sendmail.
"""

_USAGE_EXAMPLES = """
usage example:
    $ ./maily \\
        --from me@server.example \\
        --to you@server.example \\
        --subject "my subject" \\
        --message "my message"
"""

import argparse
import os
import sys

# append our module dirs to sys.path, which is the list of paths to search
# for modules this is so we can import our libraries directly
# N.B. this magic is only really passable up-front in the entrypoint module
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
PARENT_PARENT_DIR = os.path.dirname(PARENT_DIR)
sys.path.append(os.path.join(PARENT_PARENT_DIR, "py", "phl"))

import phlmail_sender
import phlsys_sendmail


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=__doc__,
        epilog=_USAGE_EXAMPLES)

    parser.add_argument(
        '--sender',
        metavar="EMAIL",
        type=str,
        required=True,
        help="address to send the mail from")

    parser.add_argument(
        '--to',
        metavar="EMAIL",
        nargs='+',
        type=str,
        required=True,
        help="addresses to send the mail to")

    parser.add_argument(
        '--cc',
        metavar="EMAIL",
        nargs='+',
        type=str,
        help="addresses to cc the mail to")

    parser.add_argument(
        '--subject',
        metavar="TEXT",
        type=str,
        required=True,
        help="subject line of the message")

    parser.add_argument(
        '--message',
        metavar="TEXT",
        type=str,
        required=True,
        help="body of the message")

    parser.add_argument(
        '--sendmail-binary',
        metavar="PROGRAM",
        type=str,
        help="program to send the mail with (e.g. sendmail, catchmail)")

    parser.add_argument(
        '--sendmail-type',
        metavar="TYPE",
        type=str,
        help="type of program to send the mail with (sendmail, catchmail), "
        "this will affect the parameters that Maily will use.")

    args = parser.parse_args()

    if args.sendmail_type:
        phlsys_sendmail.Sendmail.set_default_params_from_type(
            args.sendmail_type)

    mailsender = phlmail_sender.MailSender(
        phlsys_sendmail.Sendmail(args.sendmail_binary),
        args.sender)
    mailsender.send(
        subject=args.subject,
        message=args.message,
        to_addresses=args.to,
        cc_addresses=args.cc)


if __name__ == "__main__":
    sys.exit(main())

# -----------------------------------------------------------------------------
# Copyright (C) 2013-2014 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------ END-OF-FILE ----------------------------------
