#!/usr/bin/env bash
echo ========================================================== >> savemail.txt
echo -------------------------- SAVE MAIL --------------------- >> savemail.txt
cat - >> savemail.txt
echo ========================================================== >> savemail.txt
echo >> savemail.txt
