#! /usr/bin/python3
"""Entrypoint for the arcyd docker container."""

import argparse
import os
import signal
import subprocess
import sys
import time


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'REPO_URL',
        help='URL of the config repository to git clone')
    args = parser.parse_args()

    repo_dir = '/var/arcyd/'

    setup_git_user(
        os.environ['ARCYD_EMAIL'],
        os.environ['ARCYD_NAME'])

    if not os.path.exists(repo_dir):
        setup_repo(args.REPO_URL, repo_dir)

    os.chdir(repo_dir)

    got_sigterm = False
    def handle_sigterm(unused1, unused2):
        nonlocal got_sigterm
        got_sigterm = True

    signal.signal(signal.SIGTERM, handle_sigterm)

    arcyd = subprocess.Popen(['arcyd', 'start', '--foreground'])
    while arcyd.poll() is None:
        if got_sigterm:
            arcyd_stop = subprocess.Popen([
                'arcyd', 'stop', '--message', 'SIGTERM / probably docker stop',
            ])

            # If we don't wait(2) on Arcyd then 'arcyd stop' will wait
            # indefinitely for Arcyd to stop, as it will have an entry in the
            # process table until it is waited on.
            arcyd.wait()

            arcyd_stop.wait()
        else:
            time.sleep(1)


def setup_git_user(email, name):
    subprocess.check_call(['git', 'config', '--global', 'user.email', email])
    subprocess.check_call(['git', 'config', '--global', 'user.name', name])


def setup_repo(repo_url, repo_dir):
        subprocess.check_call(['git', 'clone', repo_url, repo_dir])
        os.chdir(repo_dir)
        if not os.path.exists(os.path.join(repo_dir, 'configfile')):
            # Set this repository up for the first time
            subprocess.check_call([
                'arcyd', 'init',
                '--arcyd-email', os.environ['ARCYD_EMAIL'],
                '--sleep-secs', os.environ['ARCYD_SLEEP_SECS']
            ])
            subprocess.check_call(['git', 'push', 'origin', 'HEAD'])
        else:
            # This repository has config, retrieve any missing repos
            subprocess.check_call(['arcyd', 'fsck', '--fix'])


if __name__ == '__main__':
    sys.exit(main())


# -----------------------------------------------------------------------------
# Copyright (C) 2015-2016 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------ END-OF-FILE ----------------------------------
